base_model: allenai/Olmo-3-7B-Instruct-SFT
auto_resume_from_checkpoints: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true
deepspeed: /home/som1tokmynam/LLM/model_training/axolotl/deepspeed_configs/zero1.json

special_tokens:
  pad_token: "<|pad|>"
  eos_token: "<|endoftext|>"

datasets:
  - path: /home/som1tokmynam/LLM/model_training/axolotl/data/combined.jsonl
    type: chat_template
    chat_template: tokenizer_default
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value  
    roles:
      user: ["human", "user"]
      assistant: ["gpt", "assistant"]
      system: ["system"]      
    roles_to_train: ["assistant"]

dataset_prepared_path: "last_run_prepared"
output_dir: /mnt/oiseauxai1data/7b-Qlora-V2
train_on_inputs: false

adapter: qlora
load_in_4bit: true
lora_r: 128
lora_alpha: 128
lora_target_linear: true
peft_use_rslora: true

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 4
lr_scheduler: cosine
learning_rate: 4e-4
max_grad_norm: 1.0

saves_per_epoch: 20
save_total_limit: 20
warmup_ratio: 0.05
hub_model_id: Darkhn/olmo3-7B-base-Animus-V12.1-Qlora
hub_strategy: all_checkpoints
eval_strategy: "no"

bf16: auto
tf32: false

gradient_checkpointing: true
logging_steps: 1
flash_attention: true

optimizer: adamw_bnb_8bit
weight_decay: 0.0
save_safetensors: true

wandb_project: olmo3-7B-Animus-base-V12.1-Qlora
wandb_entity: CrucibleLabs
wandb_name: olmo3-7B-Animus-base-V12.1-Qlora

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
liger_cross_entropy: false  # Cut Cross Entropy overrides this
liger_fused_linear_cross_entropy: false  # Cut Cross Entropy overrides this